### ISSUE TITLE
Reading of .mat files

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/beesee#2]
Currently unable to read .mat files output by Anoop’s pipeline.

**Comment by chengsoonong** [comment]
For earlier matlab versions, use scipy to read it:
http://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html
It is often nice to use pandas to deal with data in python:
http://poquitopicante.blogspot.com.au/2014/05/loading-matlab-mat-file-into-pandas.html

For versions 7.3 onward, matlab generates a standard HDF5 file:
http://au.mathworks.com/help/matlab/import_export/mat-file-versions.html
http://mloss.org/community/blog/2009/nov/19/matlabtm-73-file-format-is-actually-hdf5-and-can-b/

In python, reading HDF5 files can be done with pytables:
http://wiki.scipy.org/Cookbook/Reading_mat_files
Pandas also reads HDF5 files, but only a particular subset (which fit into a dataframe). The other option is h5py, which I find harder to use.

Please confirm that this is working, so that we can close this issue.
